version: "3"
services:
    app:
        build: .
        container_name: nuvemPessoal
        ports: 
            - "80:80"
            - "5000:5000"
            - "5001:5001"
        volumes:
            - ./:/src
    mongo:
        image: mongo
        restart: always
        ports: 
            - "27017:27017"